import hashlib
passFile = open("genshadow",'w')
m = hashlib.md5()
m.update("kitten".encode('utf-8'))
hashedPass = m.hexdigest()
passFile.write("kitten:" + hashedPass.upper())
passFile.write("\n")
m = hashlib.md5()
m.update("password".encode('utf-8'))
hashedPass = m.hexdigest()
passFile.write("password:" + hashedPass.upper())
passFile.write("\n")
m = hashlib.md5()
m.update("love".encode('utf-8'))
hashedPass = m.hexdigest()
passFile.write("love:" + hashedPass.upper())
passFile.write("\n")
m = hashlib.md5()
m.update("sex".encode('utf-8'))
hashedPass = m.hexdigest()
passFile.write("sex:" + hashedPass.upper())
passFile.write("\n")
m = hashlib.md5()
m.update("god".encode('utf-8'))
hashedPass = m.hexdigest()
passFile.write("god:" + hashedPass.upper())
passFile.write("\n")
m = hashlib.md5()
m.update("H3lp".encode('utf-8'))
hashedPass = m.hexdigest()
passFile.write("H3lp:" + hashedPass.upper())
passFile.write("\n")
m = hashlib.md5()
m.update("sle3p".encode('utf-8'))
hashedPass = m.hexdigest()
passFile.write("sle3p:" + hashedPass.upper())
passFile.write("\n")
m = hashlib.md5()
m.update("sl3ep".encode('utf-8'))
hashedPass = m.hexdigest()
passFile.write("sl3ep:" + hashedPass.upper())
passFile.write("\n")
m = hashlib.md5()
m.update("sl33p".encode('utf-8'))
hashedPass = m.hexdigest()
passFile.write("sl33p:" + hashedPass.upper())
passFile.write("\n")
m = hashlib.md5()
m.update("Nope3".encode('utf-8'))
hashedPass = m.hexdigest()
passFile.write("Nope3:" + hashedPass.upper())
passFile.write("\n")
m = hashlib.md5()
m.update("Z".encode('utf-8'))
hashedPass = m.hexdigest()
passFile.write("Z:" + hashedPass.upper())
passFile.write("\n")
m = hashlib.md5()
m.update("adf3".encode('utf-8'))
hashedPass = m.hexdigest()
passFile.write("adf3:" + hashedPass.upper())
passFile.write("\n")
m = hashlib.md5()
m.update("B6f3".encode('utf-8'))
hashedPass = m.hexdigest()
passFile.write("B6f3:" + hashedPass.upper())
passFile.write("\n")
m = hashlib.md5()
m.update("#!@/".encode('utf-8'))
hashedPass = m.hexdigest()
passFile.write("#!@/:" + hashedPass.upper())
passFile.write("\n")
m = hashlib.md5()
m.update("T73".encode('utf-8'))
hashedPass = m.hexdigest()
passFile.write("T73:" + hashedPass.upper())
passFile.write("\n")
passFile.close()
