import hashlib
passFile = open("genshadow",'w')
m = hashlib.md5()
m.update("999999".encode('utf-8'))
hashedPass = m.hexdigest()
passFile.write(hashedPass.upper())
passFile.write("\n")
m = hashlib.md5()
m.update("99993".encode('utf-8'))
hashedPass = m.hexdigest()
passFile.write(hashedPass.upper())
passFile.write("\n")
m = hashlib.md5()
m.update("93628".encode('utf-8'))
hashedPass = m.hexdigest()
passFile.write(hashedPass.upper())
passFile.write("\n")
m = hashlib.md5()
m.update("1234".encode('utf-8'))
hashedPass = m.hexdigest()
passFile.write(hashedPass.upper())
passFile.write("\n")
m = hashlib.md5()
m.update("0000".encode('utf-8'))
hashedPass = m.hexdigest()
passFile.write(hashedPass.upper())
passFile.write("\n")
m = hashlib.md5()
m.update("9995".encode('utf-8'))
hashedPass = m.hexdigest()
passFile.write(hashedPass.upper())
passFile.write("\n")
passFile.close()
